application: golmschenk
version: 1-1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /media
  static_dir: media

- url: /fonts
  static_dir: fonts

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest

- name: markupsafe
  version: latest